/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MessageRouteImport } from './routes/message'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfirmationOrderIdRouteImport } from './routes/confirmation.$orderId'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminScanRouteImport } from './routes/_authenticated/admin.scan'
import { Route as ApiPublicWebhooksFapshiRouteImport } from './routes/api/public/webhooks/fapshi'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageRoute = MessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationOrderIdRoute = ConfirmationOrderIdRouteImport.update({
  id: '/confirmation/$orderId',
  path: '/confirmation/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminScanRoute = AuthenticatedAdminScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicWebhooksFapshiRoute = ApiPublicWebhooksFapshiRouteImport.update({
  id: '/api/public/webhooks/fapshi',
  path: '/api/public/webhooks/fapshi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/message': typeof MessageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/admin/scan': typeof AuthenticatedAdminScanRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/fapshi': typeof ApiPublicWebhooksFapshiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/message': typeof MessageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/admin/scan': typeof AuthenticatedAdminScanRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/fapshi': typeof ApiPublicWebhooksFapshiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/message': typeof MessageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/_authenticated/admin/scan': typeof AuthenticatedAdminScanRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/fapshi': typeof ApiPublicWebhooksFapshiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/message'
    | '/sitemap.xml'
    | '/admin'
    | '/confirmation/$orderId'
    | '/admin/scan'
    | '/admin/'
    | '/api/public/webhooks/fapshi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/message'
    | '/sitemap.xml'
    | '/confirmation/$orderId'
    | '/admin/scan'
    | '/admin'
    | '/api/public/webhooks/fapshi'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/message'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/confirmation/$orderId'
    | '/_authenticated/admin/scan'
    | '/_authenticated/admin/'
    | '/api/public/webhooks/fapshi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MessageRoute: typeof MessageRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ConfirmationOrderIdRoute: typeof ConfirmationOrderIdRoute
  ApiPublicWebhooksFapshiRoute: typeof ApiPublicWebhooksFapshiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message': {
      id: '/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof MessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$orderId': {
      id: '/confirmation/$orderId'
      path: '/confirmation/$orderId'
      fullPath: '/confirmation/$orderId'
      preLoaderRoute: typeof ConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/scan': {
      id: '/_authenticated/admin/scan'
      path: '/scan'
      fullPath: '/admin/scan'
      preLoaderRoute: typeof AuthenticatedAdminScanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhooks/fapshi': {
      id: '/api/public/webhooks/fapshi'
      path: '/api/public/webhooks/fapshi'
      fullPath: '/api/public/webhooks/fapshi'
      preLoaderRoute: typeof ApiPublicWebhooksFapshiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminScanRoute: typeof AuthenticatedAdminScanRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminScanRoute: AuthenticatedAdminScanRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MessageRoute: MessageRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ConfirmationOrderIdRoute: ConfirmationOrderIdRoute,
  ApiPublicWebhooksFapshiRoute: ApiPublicWebhooksFapshiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
